# Generated by Django 2.2.4 on 2020-04-04 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missing',
            name='image1',
            field=models.ImageField(blank=True, help_text='사진1', null=True, upload_to='missingBoard/images'),
        ),
        migrations.AddField(
            model_name='missing',
            name='image2',
            field=models.ImageField(blank=True, help_text='사진2', null=True, upload_to='missingBoard/images'),
        ),
        migrations.AddField(
            model_name='missing',
            name='image3',
            field=models.ImageField(blank=True, help_text='사진3', null=True, upload_to='missingBoard/images'),
        ),
    ]
