# Generated by Django 2.2.4 on 2020-04-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0002_auto_20200405_0314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='missing',
            name='age',
            field=models.CharField(default='', help_text='나이', max_length=10),
        ),
        migrations.AlterField(
            model_name='missing',
            name='weight',
            field=models.CharField(default='', help_text='몸무게', max_length=20),
        ),
    ]
