# Generated by Django 2.2.4 on 2020-05-06 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0003_auto_20200411_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Community',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='', help_text='작성자 uid', max_length=100)),
                ('writing_date', models.DateTimeField(help_text='작성한 날짜')),
                ('writing_title', models.CharField(default='', help_text='글 제목', max_length=20)),
                ('writing_content', models.CharField(default='', help_text='글 내용', max_length=100)),
                ('img1', models.ImageField(blank=True, help_text='사진1', null=True, upload_to='communityBoard/images')),
                ('img2', models.ImageField(blank=True, help_text='사진2', null=True, upload_to='communityBoard/images')),
                ('img3', models.ImageField(blank=True, help_text='사진3', null=True, upload_to='communityBoard/images')),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='userName',
            field=models.CharField(default='', max_length=10),
        ),
    ]
