# Generated by Django 2.2.4 on 2020-05-07 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0004_auto_20200507_0149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='community',
            old_name='writing_content',
            new_name='community_content',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='writing_date',
            new_name='community_date',
        ),
        migrations.RenameField(
            model_name='community',
            old_name='writing_title',
            new_name='community_title',
        ),
    ]
