# Generated by Django 2.2.4 on 2020-05-27 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0008_auto_20200519_1946'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='뉴스 제목', max_length=100)),
                ('link', models.URLField(help_text='뉴스 링크')),
            ],
        ),
    ]
