# Generated by Django 2.2.4 on 2020-05-27 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0009_newsdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsdata',
            name='link',
        ),
        migrations.AlterField(
            model_name='newsdata',
            name='title',
            field=models.CharField(help_text='뉴스 제목', max_length=200),
        ),
    ]
