# Generated by Django 2.2.4 on 2020-05-27 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveme_app', '0010_auto_20200527_1535'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsdata',
            name='link',
            field=models.URLField(default='', help_text='뉴스 링크', null=True),
        ),
    ]
